### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by Julien00859** [readthedocs-fr/read-the-bin#15] opened 2021-01-11 17:51 UTC
Hello there,

I sent a message which was only containing python-styled markdown code:

    ```python
    # the content is useless
    ```

The bot successfully created the bin at the identifier `netype` but the link set by the bot was <https://bin.readthedocs.fr/netpython> which lead to a 404 snippet not found page.

To reproduce, change the `ident = pronounceable_passwd(6)` line of `bin/models.py` around line 19 by `ident = "netype"` and send a python-styled markdown code.

**Comment by Mesteery** [comment] 2021-01-11 18:04
This was already fixed by https://github.com/readthedocs-fr/read-the-bin/pull/14.
This error was caused by https://github.com/readthedocs-fr/read-the-bin/commit/e6fd8c925e377388d4a87c8cb172fa08a0dd77fb#diff-1ebfafe54e21d0426f369eee4abb9f822679c1e4a8b35be18d7620643d298c28R113.

**Closed** 2021-01-11 18:33 UTC
